### ISSUE TITLE
Simple guide

### ISSUE THREAD

**Issue by dayeggpi** [alterratz/smtp2telegram#1]
Hi,

Could you please provide simple guide on how to use ? how to run it ? should we run the py or the service ? 

thanks a lot !

**Comment by alterratz** [comment]
smtp_2_telegram.py  is a stand-alone mail server which may be started from systemd (using the provides .service file) or from the command line running the python file directly from python3. It listens on port 10025 and forward incomming smtp messages to telegram.

The configuration (port, listen address, telegram api key and chat id) is set within the script, so it takes no command line arguments. It is probably a good idea not to change the listen address from localhost to any other adress since security was not on the top development goals.

**Comment by dayeggpi** [comment]
thank you for the details, much appreciated
